repos:
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.5.1
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: flake8
    -   id: debug-statements
    -   id: check-ast
