from distutils.core import setup
setup(name='dui_test',
      version='1.0',
      license="GPL 2.0",
      description="Dials User Interface, pre - release Test",
      author='Luis Fuentes-Montero (Luiso)',
      author_email='luis.fuentes-montero@diamond.ac.uk',
      url='none yet',
      platforms='GNU/Linux & Mac OS',

      py_modules= ['dui',
                   'mini_idials_w_GUI.__init__',
                   'mini_idials_w_GUI.cli_utils',
                   'mini_idials_w_GUI.custom_widgets',
                   'mini_idials_w_GUI.dynamic_reindex_gui',
                   'mini_idials_w_GUI.gui_utils',
                   'mini_idials_w_GUI.m_idials_gui',
                   'mini_idials_w_GUI.m_idials',
                   'mini_idials_w_GUI.outputs_gui',
                   'mini_idials_w_GUI.simpler_param_widgets',
                   'mini_idials_w_GUI.params_live_gui_generator',
                   'mini_idials_w_GUI.outputs_n_viewers.__init__',
                   'mini_idials_w_GUI.outputs_n_viewers.compyling_boost_ext',
                   'mini_idials_w_GUI.outputs_n_viewers.img_viewer',
                   'mini_idials_w_GUI.outputs_n_viewers.img_view_tools',
                   'mini_idials_w_GUI.outputs_n_viewers.info_handler',
                   'mini_idials_w_GUI.outputs_n_viewers.web_page_view',],
      data_files=[('logos', ['mini_idials_w_GUI/DIALS_Logo_smaller_centred_grayed.png',
                             'mini_idials_w_GUI/DIALS_Logo_smaller_centred.png',
                             'mini_idials_w_GUI/find_spots_grayed.png',
                             'mini_idials_w_GUI/find_spots.png',
                             'mini_idials_w_GUI/import_grayed.png',
                             'mini_idials_w_GUI/import.png',
                             'mini_idials_w_GUI/index_grayed.png',
                             'mini_idials_w_GUI/index.png',
                             'mini_idials_w_GUI/integrate_grayed.png',
                             'mini_idials_w_GUI/integrate.png',
                             'mini_idials_w_GUI/refine_grayed.png',
                             'mini_idials_w_GUI/refine.png',
                             'mini_idials_w_GUI/reindex_grayed.png',
                             'mini_idials_w_GUI/reindex.png',
                             'mini_idials_w_GUI/re_try_grayed.png',
                             'mini_idials_w_GUI/re_try.png',
                             'mini_idials_w_GUI/stop_grayed.png',
                             'mini_idials_w_GUI/stop.png'])],
     )

