from distutils.core import setup
setup(name='dui_test',
      version='1.0',
      license="GPL 2.0",
      description="Dials User Interface, pre - release Test",
      author='Luis Fuentes-Montero (Luiso)',
      author_email='luis.fuentes-montero@diamond.ac.uk',
      url='none yet',
      platforms='GNU/Linux & Mac OS',
      py_modules=['python_qt_bind',
                  'custom_widgets',
                  'dynamic_reindex_gui',
                  'idials_gui',
                  'outputs_gui',
                  'idials_main_widget',
                  'simpler_param_widgets',
                  'outputs_n_viewers.compyling_boost_ext',
                  'outputs_n_viewers.img_viewer',
                  'outputs_n_viewers.img_view_tools',
                  'outputs_n_viewers.info_handler',
                  'outputs_n_viewers.web_page_view',
                  'params_live_gui_generator'],
      data_files=[('logos', ['resources/DIALS_Logo_smaller_centred.png',
                   'resources/export.png', 'resources/find_spots.png',
                   'resources/import.png', 'resources/index.png',
                   'resources/integrate.png', 'resources/refine.png',
                   'resources/refine_v_sets.png',
                   'resources/reindex.png'])],
     )

'''

  #mini_idials_gui.sh
  #mini_idials.sh

a= ['cli_utils',
  'custom_widgets',
  'dynamic_reindex_gui',
  'gui_utils',
  'm_idials_gui',
  'm_idials',
  'outputs_gui',
  'simpler_param_widgets',
  'params_live_gui_generator',
  'outputs_n_viewers.compyling_boost_ext',
  'outputs_n_viewers.img_viewer',
  'outputs_n_viewers.img_view_tools',
  'outputs_n_viewers.info_handler',
  'outputs_n_viewers.__init__',
  'outputs_n_viewers.web_page_view',]


  'resources/DIALS_Logo_smaller_centred_grayed.png',
  'resources/DIALS_Logo_smaller_centred.png',
  'resources/export.png',
  'resources/find_spots_grayed.png',
  'resources/find_spots.png',
  'resources/import_grayed.png',
  'resources/import.png',
  'resources/index_grayed.png',
  'resources/index.png',
  'resources/integrate_grayed.png',
  'resources/integrate.png',
  'resources/refine_grayed.png',
  'resources/refine.png',
  'resources/refine_v_sets.png',
  'resources/reindex_grayed.png',
  'resources/reindex.png',
  'resources/re_try_grayed.png',
  'resources/re_try.png',
  'resources/stop_grayed.png',
  'resources/stop.png',

'''

